"""Extract match score from LLM insights text."""
from __future__ import annotations

import re

import structlog

LOGGER = structlog.get_logger(__name__)


class ScoreExtractor:
    """Extracts compatibility score from LLM-generated insights text."""

    # Regex patterns for different language formats
    PATTERNS = [
        r"Compatibilidade:\s*(\d+)/100",  # Portuguese
        r"Compatibility:\s*(\d+)/100",     # English
        r"Compatibilité:\s*(\d+)/100",     # French
        r"Compatibilidad:\s*(\d+)/100",    # Spanish
        r"##\s*\w+:\s*(\d+)/100",          # Generic heading format
        r"Score:\s*(\d+)/100",              # Alternative English
        r"Puntuación:\s*(\d+)/100",         # Alternative Spanish
    ]

    def extract(self, insights_text: str) -> int:
        """
        Extract match score from insights text.

        Searches for score patterns in the text and returns the first
        match found (0-100). Clamps value to valid range if needed.

        Args:
            insights_text: Text generated by LLM containing insights

        Returns:
            Score from 0-100, or 0 if no score found
        """
        if not insights_text:
            LOGGER.debug("score_extractor.empty_text", returning=0)
            return 0

        # Try each pattern
        for pattern in self.PATTERNS:
            match = re.search(pattern, insights_text, re.IGNORECASE)
            if match:
                try:
                    score = int(match.group(1))
                    # Clamp to valid range [0, 100]
                    clamped = max(0, min(100, score))

                    LOGGER.debug(
                        "score_extractor.found",
                        pattern=pattern,
                        raw_score=score,
                        clamped_score=clamped,
                    )

                    return clamped
                except (ValueError, IndexError) as e:
                    LOGGER.warning(
                        "score_extractor.parse_error",
                        pattern=pattern,
                        error=str(e),
                    )
                    continue

        LOGGER.debug("score_extractor.not_found", text_length=len(insights_text))
        return 0

    @staticmethod
    def format_score(score: int) -> str:
        """
        Format score with interpretation.

        Args:
            score: Score from 0-100

        Returns:
            Formatted string with interpretation
        """
        if score >= 80:
            interpretation = "Excellent match"
        elif score >= 60:
            interpretation = "Good match"
        elif score >= 40:
            interpretation = "Fair match"
        elif score > 0:
            interpretation = "Poor match"
        else:
            interpretation = "No match data"

        return f"{score}/100 - {interpretation}"


__all__ = ["ScoreExtractor"]
